version: "3.8"
services:
  web:
    build: .
    container_name: integrador-mvc
    ports:
      - 3000:3000
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app